(function() {var implementors = {};
implementors["failure"] = [];
implementors["os_balloon"] = [{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"os_balloon/error/enum.Logic.html\" title=\"enum os_balloon::error::Logic\">Logic</a>",synthetic:false,types:["os_balloon::error::Logic"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"os_balloon/error/enum.Gps.html\" title=\"enum os_balloon::error::Gps\">Gps</a>",synthetic:false,types:["os_balloon::error::Gps"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"os_balloon/error/enum.Config.html\" title=\"enum os_balloon::error::Config\">Config</a>",synthetic:false,types:["os_balloon::error::Config"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"os_balloon/error/enum.Fs.html\" title=\"enum os_balloon::error::Fs\">Fs</a>",synthetic:false,types:["os_balloon::error::Fs"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"os_balloon/error/enum.Log.html\" title=\"enum os_balloon::error::Log\">Log</a>",synthetic:false,types:["os_balloon::error::Log"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"os_balloon/error/enum.LastState.html\" title=\"enum os_balloon::error::LastState\">LastState</a>",synthetic:false,types:["os_balloon::error::LastState"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"os_balloon/error/enum.Fona.html\" title=\"enum os_balloon::error::Fona\">Fona</a>",synthetic:false,types:["os_balloon::error::Fona"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"os_balloon/error/enum.Raspicam.html\" title=\"enum os_balloon::error::Raspicam\">Raspicam</a>",synthetic:false,types:["os_balloon::error::Raspicam"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"os_balloon/error/enum.Init.html\" title=\"enum os_balloon::error::Init\">Init</a>",synthetic:false,types:["os_balloon::error::Init"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
