(function() {var implementors = {};
implementors["libudev"] = [{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/sys/unix/ext/io/trait.AsRawFd.html\" title=\"trait std::sys::unix::ext::io::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"libudev/struct.MonitorSocket.html\" title=\"struct libudev::MonitorSocket\">MonitorSocket</a>&lt;'a&gt;",synthetic:false,types:["libudev::monitor::MonitorSocket"]},];
implementors["mio"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/sys/unix/ext/io/trait.AsRawFd.html\" title=\"trait std::sys::unix::ext::io::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"mio/struct.Poll.html\" title=\"struct mio::Poll\">Poll</a>",synthetic:false,types:["mio::poll::Poll"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/sys/unix/ext/io/trait.AsRawFd.html\" title=\"trait std::sys::unix::ext::io::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"mio/net/struct.TcpStream.html\" title=\"struct mio::net::TcpStream\">TcpStream</a>",synthetic:false,types:["mio::net::tcp::TcpStream"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/sys/unix/ext/io/trait.AsRawFd.html\" title=\"trait std::sys::unix::ext::io::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"mio/net/struct.TcpListener.html\" title=\"struct mio::net::TcpListener\">TcpListener</a>",synthetic:false,types:["mio::net::tcp::TcpListener"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/sys/unix/ext/io/trait.AsRawFd.html\" title=\"trait std::sys::unix::ext::io::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"mio/net/struct.UdpSocket.html\" title=\"struct mio::net::UdpSocket\">UdpSocket</a>",synthetic:false,types:["mio::net::udp::UdpSocket"]},];
implementors["mio_serial"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/sys/unix/ext/io/trait.AsRawFd.html\" title=\"trait std::sys::unix::ext::io::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"mio_serial/unix/struct.Serial.html\" title=\"struct mio_serial::unix::Serial\">Serial</a>",synthetic:false,types:["mio_serial::unix::Serial"]},];
implementors["net2"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/sys/unix/ext/io/trait.AsRawFd.html\" title=\"trait std::sys::unix::ext::io::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"net2/struct.TcpBuilder.html\" title=\"struct net2::TcpBuilder\">TcpBuilder</a>",synthetic:false,types:["net2::tcp::TcpBuilder"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/sys/unix/ext/io/trait.AsRawFd.html\" title=\"trait std::sys::unix::ext::io::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"net2/struct.UdpBuilder.html\" title=\"struct net2::UdpBuilder\">UdpBuilder</a>",synthetic:false,types:["net2::udp::UdpBuilder"]},];
implementors["nix"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/sys/unix/ext/io/trait.AsRawFd.html\" title=\"trait std::sys::unix::ext::io::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"nix/pty/struct.PtyMaster.html\" title=\"struct nix::pty::PtyMaster\">PtyMaster</a>",synthetic:false,types:["nix::pty::PtyMaster"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/sys/unix/ext/io/trait.AsRawFd.html\" title=\"trait std::sys::unix::ext::io::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"nix/sys/signalfd/struct.SignalFd.html\" title=\"struct nix::sys::signalfd::SignalFd\">SignalFd</a>",synthetic:false,types:["nix::sys::signalfd::SignalFd"]},];
implementors["serialport"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/sys/unix/ext/io/trait.AsRawFd.html\" title=\"trait std::sys::unix::ext::io::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"serialport/posix/struct.TTYPort.html\" title=\"struct serialport::posix::TTYPort\">TTYPort</a>",synthetic:false,types:["serialport::posix::tty::TTYPort"]},];
implementors["tokio_serial"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/sys/unix/ext/io/trait.AsRawFd.html\" title=\"trait std::sys::unix::ext::io::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"tokio_serial/struct.Serial.html\" title=\"struct tokio_serial::Serial\">Serial</a>",synthetic:false,types:["tokio_serial::Serial"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
