language: rust
cache: cargo
dist: xenial
sudo: true

os: linux
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - zlib1g-dev
      - libudev-dev

# Run builds for all the supported trains
rust:
  - 1.31.0
  - stable
  - beta
  - nightly

stages:
- test
- deploy

env:
- DEFAULT_FEATURES=true
- DEFAULT_FEATURES=true FEATURES="no_power_off"
- DEFAULT_FEATURES=false
- DEFAULT_FEATURES=false FEATURES="no_power_off"
- DEFAULT_FEATURES=false FEATURES="all_hardware"
- DEFAULT_FEATURES=false FEATURES="all_hardware no_power_off"
# Testing with fona
- DEFAULT_FEATURES=false FEATURES="fona"
- DEFAULT_FEATURES=false FEATURES="fona gps"
- DEFAULT_FEATURES=false FEATURES="fona gps raspicam"
- DEFAULT_FEATURES=false FEATURES="fona gps telemetry"
- DEFAULT_FEATURES=false FEATURES="fona raspicam"
- DEFAULT_FEATURES=false FEATURES="fona raspicam telemetry"
- DEFAULT_FEATURES=false FEATURES="fona telemetry"
# Testing without FONA, with GPS
- DEFAULT_FEATURES=false FEATURES="gps"
- DEFAULT_FEATURES=false FEATURES="gps telemetry"
- DEFAULT_FEATURES=false FEATURES="gps telemetry raspicam"
- DEFAULT_FEATURES=false FEATURES="gps raspicam"
# Testing without FONA or GPS
- DEFAULT_FEATURES=false FEATURES="raspicam"
- DEFAULT_FEATURES=false FEATURES="raspicam telemetry"
- DEFAULT_FEATURES=false FEATURES="telemetry"

# Extra jobs to include
jobs:
  include:
  # Upload documentation
  - name: "Documentation upload"
    rust: stable
    stage: deploy
    env: CACHE_NAME=DOCS
    script: ./travis-helper.sh documentation
    deploy: &pages
      provider: pages
      github-token: $GH_TOKEN
      local-dir: target/doc/
      skip_cleanup: true
      keep-history: true
      on:
        repo: OpenStratos/server-rs
        branch: develop

# The main build
script:
  - ./travis-helper.sh fmt_check
  - ./travis-helper.sh clippy_check
  - ./travis-helper.sh test

notifications:
  email:
    recipients:
      - razican@protonmail.ch
      - eneko.cruz@opendeusto.es
    on_success: change
    on_failure: always
