[package]
name = "os_balloon"
version = "2.0.0-dev"
authors = [
    "Razican <razican@protonmail.ch>",
]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/OpenStratos/server-rs"
homepage = "https://openstratos.org/"
description = """\
Stratospheric balloon control software.
"""
keywords = ["OpenStratos", "stratosphere", "raspberry", "balloon", "science"]
categories = ["science"]

[badges]
travis-ci = { repository = "OpenStratos/server-rs", branch = "master" }
codecov = { repository = "OpenStratos/server-rs", branch = "master", service = "github" }
is-it-maintained-issue-resolution = { repository = "OpenStratos/server-rs" }
is-it-maintained-open-issues = { repository = "OpenStratos/server-rs" }

[lib]
name = "os_balloon"
path = "src/lib.rs"

[[bin]]
name = "launcher"
path = "src/main.rs"

[features]
default = ["gps", "raspicam", "fona", "telemetry"]
# GPS feature.
gps = []
# Raspberry Pi camera.
raspicam = []
# Adafruit FONA GSM module.
fona = []
# Do not send SMSs (so that it does not cost money)
no_sms = ["fona"]
# Transparent serial telemetry.
telemetry = []
# Do not ever power off the system, only exit.
no_power_off = []

[dependencies]
error-chain = "0.10"
lazy_static = "0.2"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
log = "0.3"
colored = "1.5"
chrono = "0.4"
libc = "0.2.24"
sysfs_gpio = "0.5.1"
tokio-serial = "0.5.0"

[dependencies.log4rs]
version = "0.7"
default_features = false
features = ["file", "file_appender", "console_appender", "threshold_filter"]

# The release profile, used for `cargo build`.
[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 1
panic = 'unwind'

# The release profile, used for `cargo build --release`.
[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
panic = 'unwind'
