##---- OpenStratos configuration file ----##

#### GENERAL SETTINGS ####
# Debug mode.
debug =  true
# Data directory.
data_dir = "data"

## Battery configuration ##
[battery]
# Minimum voltage for the main battery.
main_min = 1.952777778 # 7.4*2660/(2660+7420) - Measured Ohms in voltage divider
# Maximum voltage for the main battery.
main_max = 2.216666667 # 8.4*2660/(2660+7420) - Measured Ohms in voltage divider
# Minimum voltage for the GSM battery.
fona_min = 3.7
# Maximum voltage for the GSM battery.
fona_max = 4.2
# Minimum admisible percentage for main battery for launch.
main_min_percent = 80
# Minimum admisible percentage for FONA battery for launch.
fona_min_percent = 75

## Picture configuration ##
[picture]
# Static pictures dimensions, in pixels.
height = 2464
width = 3280
# Camera rotation, in degrees.
rotation = 180
# Configuration options for EXIF information in pictures.
exif = true
# Picture quality
quality = 95
# Wether to add the raw camera data to the image metadata.
raw = true
# Picture exposure.
exposure = "antishake"
# Picture brightness.
brightness = 50
# Picture contrast.
contrast = 50
# Picture sharpness.
#sharpness = 0
# Picture saturation.
#saturation = 0
# Picture ISO.
#iso = 400
# Video EV compensation.
#ev = 0
# Automatic picture white balance
white_balance = "horizon"
# Interval between pictures, in seconds.
interval = 300 # 5 minutes
# Repeat each picture after these seconds (for issues with probe movement). (optional)
repeat = 30
# First picture timeout in seconds, after the launch.
first_timeout = 120 # 2 minutes

## Video configuration ##
[video]
# Video dimensions, in pixels.
width = 1920
height = 1080
# Camera rotation, in degrees.
rotation = 180
# Video framerate, in frames per second.
fps = 30
# Video bitrate, in bits per second.
bitrate = 20000000
# Video exposure.
exposure = "antishake"
# Video brightness.
brightness = 50
# Video contrast.
contrast = 50
# Video sharpness.
#sharpness = 0
# Video saturation.
#saturation = 0
# Video ISO.
#iso = 400
# Video stabilization
stabilization = true
# Video EV compensation.
#ev = 0
# Automatic video white balance
white_balance = "horizon"

## Flight configuration ##
[flight]
# Approximate expected flight length, in minutes.
length = 300 # 5 hours
# Approximate expected maximum height, in meters.
expected_max_height = 35000

## GPS configuration ##
[gps]
# GPS UART serial console path.
uart = "/dev/ttyAMA0"
# GPS serial baud rate.
baud_rate = 9600
# GPS power control GPIO pin number.
power_gpio = 3

##  FONA module configuration ##
[fona]
# FONA UART serial console path.
uart = "/dev/ttyUSB0"
# FONA serial baud rate.
baud_rate = 9600
# FONA power control GPIO pin number.
power_gpio = 7
# FONA status GPIO pin number.
status_gpio = 21
# SMS receiver phone number.
sms_phone = ""
# Operator GSM location service domain.
location_service = "gprs-service.com"

## Telemetry configuration ##
[telemetry]
# Telemetry UART serial console path.
uart = "/dev/ttyUSB1"
# Telemetry serial baud rate.
baud_rate = 230400
